modLoader = "javafml" #mandatory
loaderVersion = "[4,)"
license = "CC-BY-NC-SA-4.0" # Review your options at https://choosealicense.com/.
[[mods]] #mandatory
modId = "ecstatic" #mandatory
version = "1.4.0" #mandatory
displayName = "Ecstatic" #mandatory
logoFile = "ecstatic.png"
credits = "" #optional
authors = "angryalchemist" #optional
description = '''Massive render-distance terrain LOD via surface-only generation and custom flat storage, without external pregen tools.''' #mandatory (Supports multiline text)

[[dependencies.ecstatic]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.ecstatic]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1, 1.21.2)"
ordering = "NONE"
side = "BOTH"
